// <auto-generated />
namespace SubscriptionTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ConfirmPassword : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConfirmPassword));
        
        string IMigrationMetadata.Id
        {
            get { return "202010130736596_ConfirmPassword"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
